const MIN_MEMBERS_TO_START = 2
const START_COUNTDOWN_MS = 10 * 1000
const TRANSFER_CONFIRMATION_TIMEOUT_MS = 2 * 60 * 1000

module.exports = {
	MIN_MEMBERS_TO_START,
	START_COUNTDOWN_MS,
	TRANSFER_CONFIRMATION_TIMEOUT_MS
}