const ACTIVE_GAME_REDIRECT_DELAY_MS = 3 * 1000
const REFRESH_INTERVAL_MS = 5 * 1000

const APL_VERSION = 'Ver 1.0.1'

module.exports = {
  ACTIVE_GAME_REDIRECT_DELAY_MS,
  REFRESH_INTERVAL_MS,
  APL_VERSION
}