const ACTIVE_GAME_REDIRECT_DELAY_MS = 3 * 1000
const JOINER_START_COUNTDOWN_MS = 10 * 1000
const REFRESH_INTERVAL_MS = 5 * 1000

module.exports = {
  ACTIVE_GAME_REDIRECT_DELAY_MS,
  JOINER_START_COUNTDOWN_MS,
  REFRESH_INTERVAL_MS
}