const ACTIVE_GAME_REDIRECT_DELAY_MS = 3 * 1000
const REFRESH_INTERVAL_MS = 5 * 1000
const DEBUG_MODE = false

const APL_VERSION = 'Ver 1.0.4'

module.exports = {
  ACTIVE_GAME_REDIRECT_DELAY_MS,
  REFRESH_INTERVAL_MS,
  DEBUG_MODE,
  APL_VERSION
}